# Make this unique, and don't share it with anybody.
SECRET_KEY = "NOT FOR PRYING EYES"

DATABASE_URL = 'postgres://DB_NAME:PASSWORD@fit-dev-db.cx7ezqzbijxw.us-west-2.rds.amazonaws.com/fitdb'

ACCOUNT_OPEN_SIGNUP = True

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = 'KEY GOES HERE'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = 'SECRET HERE'

MIXPANEL_TOKEN = 'TOKEN HERE'
MIXPANEL_SECRET = 'SECRET HERE'

SENDGRID_API_KEY = 'SG.'


