survey = {"status":200,"message":"Success","data":[{"Id":259,"UserId":361,"SubCategoryId":0,"Score":60,"SurveyId":475,"Balance":0,"CognitiveFit":15,"CognitiveBal":0,"EmotionalFit":15,"EmotionalBal":0,"PhysicalFit":15,"PhysicalBal":0,"FinancialFit":15,"FinancialBal":0,"CreateDate":"/Date(1482428841000)/"}]}

data = [
{"id":"cognitive",
"order":1,
"score":15.89,
"color":"#FFB163",
"label":"Cognitive",
"weight":4,
"balance":0.72,
"subScores":[{"SubCategory":{"Id":1,
"Name":"Learning Strategies",
"CategoryId":1,
"Multiplier":5},
"Score":12.86,
"ShortTermValue":0,
"Color":"#FFD8B1",
"Description":"This captures how effective and aware you are of acquiring new knowledge and skills. Successful learning requires a self-evaluation process where adjustments are made when necessary.",
"Weight":0},{"SubCategory":{"Id":2,
"Name":"Intellectual Engagement",
"CategoryId":1,
"Multiplier":5},
"Score":17.5,
"ShortTermValue":0,
"Color":"#FFC082",
"Description":"This captures your tendency to challenge yourself with mentally difficult tasks. Intellectual engagement represents how much you enjoy problem solving, critically thinking, and undertaking cognitive puzzles.",
"Weight":0},{"SubCategory":{"Id":3,
"Name":"Effortful Control",
"CategoryId":1,
"Multiplier":5},
"Score":15.83,
"ShortTermValue":0,
"Color":"#FFC082",
"Description":"This assesses self-regulation, which includes goal-setting, planning, and efficiently implementing procedures to achieve a desired outcome. Having good effortful control is also related to high amounts of willpower to not engage in activities that are unrelated to making forward progress towards a long-term desired state.",
"Weight":0},{"SubCategory":{"Id":4,
"Name":"Attention",
"CategoryId":1,
"Multiplier":5},
"Score":15.83,
"ShortTermValue":0,
"Color":"#FFC082",
"Description":"This captures the ability to pay attention to one stimulus over another, the ability to stay focused on a task for many hours without being distracted, and being able to regain attention quickly when being called to a different task.",
"Weight":0},{"SubCategory":{"Id":5,
"Name":"Autonomy",
"CategoryId":1,
"Multiplier":5},
"Score":18.33,
"ShortTermValue":0,
"Color":"#FFC082",
"Description":"This assesses the degree to which people feel self-determined. This means not only do you feel in control of your life, but you also make decisions demonstrating you are self-governing rather than a passive participant in your life.",
"Weight":0},{"SubCategory":{"Id":6,
"Name":"Social Cognition",
"CategoryId":1,
"Multiplier":5},
"Score":15,
"ShortTermValue":0,
"Color":"#FFC082",
"Description":"This measures cognitive skills relating to interacting with other people. This includes understanding other people's intentions and desires as well as the degree to which you are skilled at interacting with others. ",
"Weight":0}],
"rampingUp":"Negative thinking patterns might be dragging other areas of your life down, and you might have difficulty gaining control over your thoughts, such as staying focused and not being distracted. In addition to being uninterested in learning new things, you may not believe in your own ability to reach competency in various tasks. You have the tendency to avoid obtaining feedback from other people because you believe your perspective is better than others. You may not be aware of the limitations you set on yourself by believing that your situation is out of your control; thereby, significantly undermining your potential to bring growth and improvements to your life.",
"developer":"Although you might set goals and wish to learn new things, you may not engage in the most productive thinking processes to help you attain those goals. Thus, your cognitive habits might be sabotaging your ability to reach your goals. You may be easily distracted and have a hard time concentrating when under pressure. You can be prone to evading challenges, especially when it involves learning new things. You may be hesitant to seek other people's opinions and perspective because this threatens your belief system. There might be times that you second guess your ability to succeed, which undermines your likelihood of setting challenging goals. Thus, you may accomplish much less than you are capable.",
"experienced":"Your cognitive habits are progressing towards a highly efficient mental framework, though there are still areas that need improvement. You might be likely to set the bar high in terms of your goals, and are inclined toward learning new things, but some of your thinking might undercut your ability to fully reach your potential. Though you are focused on attaining what you set out to accomplish, you might find there are times you are easily distracted or you might have difficulty staying focused for long periods. At times you may feel a victim of circumstance and might need to work on developing a growth mindset where you feel more in control of your own thinking, decisions, and, therefore, your situation.",
"FITastic":"Your cognitive habits are effective, productive, and fully integrated with your purpose and goals. Your method of approaching problems is likely to help you find solutions to difficult situations. You create environments that help you thrive, and your thinking directly impacts your likelihood to be successful in what you set out to accomplish. You seek out feedback and are eager to understand other people's perspectives. You are able to focus your attention on the task at hand until it is accomplished. You enjoy learning, do not shy away from challenges, and believe in your ability to succeed. In short, you are cognitively FITastic."},{"id":"emotional",
"order":3,
"score":14.31,
"color":"#63C7E7",
"label":"Emotional",
"weight":4,
"balance":0.72,
"subScores":[{"SubCategory":{"Id":7,
"Name":"General Emotional Health",
"CategoryId":2,
"Multiplier":5},
"Score":14,
"ShortTermValue":0,
"Color":"#B1E3F3",
"Description":"This is an index of how you are doing overall in terms of your emotional wellbeing. ",
"Weight":0},{"SubCategory":{"Id":8,
"Name":"Self Compassion \u0026 Self Awareness",
"CategoryId":2,
"Multiplier":5},
"Score":12.5,
"ShortTermValue":0,
"Color":"#B1E3F3",
"Description":"This taps how kindly you treat yourself and how well you know your own feelings. This includes your ability to control anger outbursts and whether or not understanding yourself is important to you.",
"Weight":0},{"SubCategory":{"Id":9,
"Name":"Stress Resilience",
"CategoryId":2,
"Multiplier":5},
"Score":16,
"ShortTermValue":0,
"Color":"#91D7EE",
"Description":"This measures your ability to cope with and adapt to life's challenges and difficulties. ",
"Weight":0},{"SubCategory":{"Id":10,
"Name":"Gratitude \u0026 Positivity",
"CategoryId":2,
"Multiplier":5},
"Score":15.83,
"ShortTermValue":0,
"Color":"#91D7EE",
"Description":"This measures how grateful you are to others for your successes and how often you incorporate gratitude practices into your daily life.",
"Weight":0},{"SubCategory":{"Id":11,
"Name":"Spiriturality",
"CategoryId":2,
"Multiplier":5},
"Score":12.5,
"ShortTermValue":0,
"Color":"#B1E3F3",
"Description":"This can be understood as the search for meaning and purpose, which exists beyond our personal selves. ",
"Weight":0},{"SubCategory":{"Id":12,
"Name":"Social Engagement",
"CategoryId":2,
"Multiplier":5},
"Score":15,
"ShortTermValue":0,
"Color":"#91D7EE",
"Description":"This is related to whether or not you have people in your life with which you can share your worries and concerns. It also includes how comforted you feel when you share your worries with a friend or family member.",
"Weight":0}],
"rampingUp":"At this point in your life you may be experiencing worries or fears and may have a difficult time understanding your emotions. You may be lacking in the skills which allow you to be kind to yourself, and your ability to deal with stress is not yet developed. Sensing a disconnect from your emotions may make you feel out of control at times and may interfere with your social interactions and your ability to get close to others. You may not be experiencing much gratitude in your day-to-day life, and negative thoughts may be your default position. You may not have a spiritual practice at this time or may not be fulfilled by it if you do. You are beginning  your journey to emotional FITness.",
"developer":"Although you may be interested in emotional fitness, you are still in the beginning stages of your journey. Emotional stability may be something you experience on occasion, but not consistently. Your emotional intelligence may be growing. Positivity and your ability to feel resilient to stress have the potential for growth, but they are not yet working optimally for you and may be preventing you from thriving in the other dimensions. You may be on the road to feeling more optimistic and may be working on your negativity bias, trying to turn it around to better serve your emotional health. Building your self-awareness skills, cultivating your spiritual practice, and developing your social acumen will serve you well on this and the other FIT dimensions.",
"experienced":"You have developed some emotional awareness and have a sense of self which are creating some emotional resilience and helping you to feel more consistent and balanced. You are working on being able to manage your emotional distress more easily, and you have some tools in your emotional toolbox. You may be working with your thoughts to help you change how you feel. At this point you may be able to sustain a feeling of emotional wellness for longer periods of time. Overwhelming feelings may occur less frequently, as you are still learning to regulate your nervous system. If you fall into this range, you are doing well from an Emotional FITness perspective, but your life would benefit from deepening your emotional, spiritual, and social repertoire.",
"FITastic":"A positive mindset and keen self-awareness characterize your emotional skills. If your scores fall into this range you are emotionally resilient and have a spiritual connection, which creates more meaning and productivity in your work and home life. You are reaping the benefits of gratitude practices, and you appreciate that being compassionate with yourself has its benefits. Your social skillfulness positively impacts how supported you feel and how healthy you are physically. Your emotional strengths and habits are creating a strong platform for further developing balance amongst the Cognitive, Physical, and Financial dimensions of your FIT life."},{"id":"physical",
"order":4,
"score":14.69,
"color":"#D38989",
"label":"Physical",
"weight":3,
"balance":0.72,
"subScores":[{"SubCategory":{"Id":13,
"Name":"Nutrition",
"CategoryId":3,
"Multiplier":5},
"Score":17,
"ShortTermValue":0,
"Color":"#DBA0A0",
"Description":"This subcategory measures your current diet, which includes how you nourish and hydrate your body. This provides an index of the degree to which you implement healthy nutritional choices.",
"Weight":0},{"SubCategory":{"Id":14,
"Name":"Nutrition Knowledge",
"CategoryId":3,
"Multiplier":5},
"Score":15,
"ShortTermValue":0,
"Color":"#DBA0A0",
"Description":"This measures your understanding of how you nourish and hydrate your body. This includes how well informed you are about contemporary guidelines regarding what you should and should not consume.",
"Weight":0},{"SubCategory":{"Id":15,
"Name":"Inactivity",
"CategoryId":3,
"Multiplier":5},
"Score":13,
"ShortTermValue":0,
"Color":"#E9C4C4",
"Description":"This captures how sedentary you are across an average week.  Included in this subcategory is how much you sit and engage in physically inactive activities.",
"Weight":0},{"SubCategory":{"Id":16,
"Name":"Aerobic Activity",
"CategoryId":3,
"Multiplier":5},
"Score":16.25,
"ShortTermValue":0,
"Color":"#DBA0A0",
"Description":" This measures activity levels related to cardiovascular exercise, which is defined as activities that increase heart rate and breathing rate for a sustained period of time. ",
"Weight":0},{"SubCategory":{"Id":17,
"Name":"Strength Training",
"CategoryId":3,
"Multiplier":5},
"Score":12.5,
"ShortTermValue":0,
"Color":"#E9C4C4",
"Description":"This measures activity levels related to anaerobic exercise, which is high-intensity activity that relies on energy sources stored in the body. This type of training induces muscular strength and growth. ",
"Weight":0},{"SubCategory":{"Id":32,
"Name":"Improve Self Image",
"CategoryId":3,
"Multiplier":5},
"Score":13.75,
"ShortTermValue":0,
"Color":"#E9C4C4",
"Description":"This captures satisfaction, contentment, and personal growth in how you view yourself. This index includes your personal perception regarding your body and appearance",
"Weight":0},{"SubCategory":{"Id":33,
"Name":"Improve Sleep Habits",
"CategoryId":3,
"Multiplier":5},
"Score":13.75,
"ShortTermValue":0,
"Color":"#E9C4C4",
"Description":"This measures the frequency and quality of your sleep as well as your sleep hygiene, which are environmental factors and your behaviors that impact your sleep patterns. ",
"Weight":0},{"SubCategory":{"Id":34,
"Name":"Social Aspects of Training",
"CategoryId":3,
"Multiplier":5},
"Score":16.25,
"ShortTermValue":0,
"Color":"#DBA0A0",
"Description":" This measures the community you engage with when working out, such as participating in exercise classes or working out with a friend. This also includes an index of whether or not you have conversations with others regarding your exercise routine. ",
"Weight":0}],
"rampingUp":"In this range, you may be experiencing the lack of a well-defined sense of personal ideal or archetype related to your physical body. Currently, you are at higher risk for a variety of poor health outcomes and constellations of different illnesses. You may be suffering from low self-image and diminished feelings of self-efficacy. A lack of physical activity and substandard nutrition increase the likelihood you may be suffering from mental and emotional problems. The good news is, when individuals in this category take action, the results can be massive. You have great potential for change and growth.   With changes, you can often experience quite dramatic outcomes, and virtually any well-directed action will yield positive results.  You will greatly benefit from developing a clear vision for your ideal physical state and taking positive action in that direction.",
"developer":" You probably are not consistently adhering to desirable food and exercise choices. Improvements should be focused on gaining knowledge about nutrition and exercise habits. Growth should be focused on finding realistic ways to make positive lifestyle changes.  At this time, you tend to have poor nutritional habits and low levels of physical activity, both of which contribute to low levels of energy and negative self-image. The good news is you can greatly benefit from clearly stating your desired physical outcomes.  You currently possess immense potential for development.  Even minor lifestyle changes can produce significant improvements in your overall physical health.   Creating concepts of personal physical standards and ideals, coupled with well-directed action, can produce impressive results in your life.",
"experienced":"You are currently attempting to make physical fitness a priority in your life but have ample room for improvement with nutritional components or activity levels. Often, you perform well with either nutrition or physical activity, but rarely apply equal effort to both at the same time. Therefore, consistent application of both sound nutritional and exercise habits (simultaneously) is critical to personal development.  Focus on creating more balance between nutrition and exercise, as well as making small improvements in both areas, to generate the best outcomes.  Core concepts for you include defining your desired physical outcomes as well as opportunities for improvement, then taking the necessary steps and appropriate actions in this direction.",
"FITastic":"You make physical fitness a top priority, working out everyday or most days during the week. You are acutely aware of nutrition and have healthy eating habits.  One hallmark you possess is a well-developed sense of your personal, physical ideal. You tend to have a strong mental image pertaining to how you want to look, feel, or perform physically. Sound exercise and nutritional habits have become part of your routine. In order for you to maintain a growth state,  seek out new physical challenges, continually change exercise modalities, and safely try new activities. The healthiest within this group understand the importance of consuming several servings of fruits and vegetables each day, and the necessity of sleep. You experience a high degree of balance across the subcategories within the Physical dimension."},{"id":"financial",
"order":2,
"score":15.48,
"color":"#A7D4A4",
"label":"Financial",
"weight":5,
"balance":0.72,
"subScores":[{"SubCategory":{"Id":18,
"Name":"Long Term Financial",
"CategoryId":4,
"Multiplier":5},
"Score":16.43,
"ShortTermValue":4,
"Color":"#C1E0BF",
"Description":"This assesses the knowledge, actions, and positions you have in place that promote financial security with an outlook of five years and beyond. ",
"Weight":0},{"SubCategory":{"Id":19,
"Name":"Short Term Financial",
"CategoryId":4,
"Multiplier":5},
"Score":19.33,
"ShortTermValue":4,
"Color":"#C1E0BF",
"Description":"This is designed to evaluate the needs, concerns, and ability to manage monetary challenges over a one year or shorter time horizon. ",
"Weight":0},{"SubCategory":{"Id":20,
"Name":"Reduce Sadness",
"CategoryId":4,
"Multiplier":5},
"Score":15.56,
"ShortTermValue":4,
"Color":"#C1E0BF",
"Description":"This is related to decisions and actions taken to improve and secure your current financial position. ",
"Weight":0},{"SubCategory":{"Id":21,
"Name":"Increase Happiness",
"CategoryId":4,
"Multiplier":5},
"Score":12.5,
"ShortTermValue":4,
"Color":"#D3E9D1",
"Description":"This captures the way money is used to enhance life experiences beyond financial security. ",
"Weight":0},{"SubCategory":{"Id":22,
"Name":"Social/Emotional Support",
"CategoryId":4,
"Multiplier":5},
"Score":13.57,
"ShortTermValue":4,
"Color":"#D3E9D1",
"Description":"This captures elements of financial concerns around social interactions and sleep problems.",
"Weight":0}],
"rampingUp":"You are taking your first steps toward financial FITness, but it may feel overwhelming initially. This could be a function of any or all of the following: significant debt, limited cash flow, a low paying job, no financial savings, or frequent sleepless nights.  One or a combination of these factors may be contributing to significant financial concerns that are increasing sadness and limiting your happiness. You are at a place where you need some guidance and are ready to make significant growth in your Financial FITness.",
"developer":"Although you may be striving toward financial FITness, you may need to overcome some significant hurdles.  These may include a short-term cash flow problem, no long-term financial plan, concerns over a job, or the weight of paying bills.  Your current wage may be holding you back, and you may have trouble sleeping at night because of financial worries. Although you are headed in the right direction, you are looking for some guidance in terms of moving forward on your financial goals.",
"experienced":"Your financial outlook is progressing to allow you to put yourself in a position to best maximize the other dimensions for a FIT and fulfilling life.  You may have some short-term cash concerns or the workings of a long-term financial plan. The disposable income you have may allow you to pursue a healthy lifestyle, but you may have some worries about your immediate financial future. You are looking for some guidance in how to continue your progression past a place of worry to optimal Financial FITness.",
"FITastic":"Your financial outlook puts you in a position to best maximize the other dimensions for a FIT and fulfilling life.  You have no short-term cash concerns, you have a long-term financial plan, and the disposable income you have allows you to pursue a healthy lifestyle. Your high Financial FITness puts you in an optimal place to focus on achieving BALANCE in your life through Cognitive, Emotional, and Physical FITness."}
]
