# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-02 03:01
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('open', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=1, help_text='Range: [1-6]')),
            ],
        ),
        migrations.CreateModel(
            name='CustomPrinciple',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Demographic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('email', models.TextField()),
                ('gender', models.TextField()),
                ('marital_status', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('address_line1', models.TextField()),
                ('address_line2', models.TextField()),
                ('state', models.TextField()),
                ('postal_code', models.TextField()),
                ('phone', models.TextField()),
                ('city', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.IntegerField(choices=[(1, 'Cognitive'), (2, 'Emotional'), (3, 'Physical'), (4, 'Financial')], primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('divisor', models.IntegerField(default=5)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DreamBuilder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DreamEnviroment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nutrient_people', models.TextField(blank=True)),
                ('nutrient_places', models.TextField(blank=True)),
                ('nutrient_resources', models.TextField(blank=True)),
                ('toxic_people', models.TextField(blank=True)),
                ('toxic_places', models.TextField(blank=True)),
                ('toxic_resources', models.TextField(blank=True)),
                ('dreambuilder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fit.DreamBuilder')),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(blank=True, max_length=60, validators=[django.core.validators.RegexValidator(message='Invalid Chronos name.', regex='([\\w\\.-]+)')])),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fit.Agenda')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fit.Goal')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start', models.DateTimeField(null=True)),
                ('end', models.DateTimeField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fit.Objective')),
            ],
        ),
        migrations.CreateModel(
            name='Principle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrincipleAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True)),
                ('custom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fit.CustomPrinciple')),
                ('dreambuilder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fit.DreamBuilder')),
                ('principle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fit.Principle')),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('delta', models.IntegerField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fit.Plan')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField(default=0, help_text='Sequence Order')),
                ('content', models.TextField()),
                ('is_reversed', models.BooleanField(default=False, help_text='answer.Value = -(answer.Value - 6)')),
                ('is_active', models.NullBooleanField(default=True)),
                ('is_corp', models.BooleanField(default=False)),
                ('weight', models.IntegerField(default=1)),
                ('style', models.IntegerField(choices=[(0, 'Normal'), (1, 'NoneToALot'), (2, 'LessWorriedMuchHappier'), (3, 'Creditors'), (4, 'Mortgage'), (5, 'Success'), (6, 'NA'), (7, 'Television')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('multiplier', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_corp', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fit.Question')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fit.Survey')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fit.Goal')),
            ],
        ),
        migrations.CreateModel(
            name='Vision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('text', models.TextField(blank=True)),
                ('dreambuilder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fit.DreamBuilder')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreColor',
            fields=[
                ('dimension', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='fit.Dimension')),
                ('group', models.TextField(blank=True, help_text='red, blue, green, etc.', max_length=10)),
                ('low', models.TextField(help_text='score < 10', max_length=7)),
                ('medium', models.TextField(help_text='score >= 10 && score < 15', max_length=7)),
                ('high', models.TextField(help_text='score >= 15 && score < 20', max_length=7)),
                ('max', models.TextField(help_text='score >= 20', max_length=7)),
            ],
        ),
        migrations.AddField(
            model_name='subcategory',
            name='dimension',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fit.Dimension'),
        ),
        migrations.AddField(
            model_name='question',
            name='dimension',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fit.Dimension'),
        ),
        migrations.AddField(
            model_name='question',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fit.SubCategory'),
        ),
        migrations.AddField(
            model_name='plan',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fit.Task'),
        ),
        migrations.AddField(
            model_name='objective',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fit.SubCategory'),
        ),
        migrations.AddField(
            model_name='objective',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goal',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fit.SubCategory'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fit.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fit.Survey'),
        ),
    ]
