# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-05 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0002_resource'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agenda',
            options={'get_latest_by': 'created'},
        ),
        migrations.AlterModelOptions(
            name='survey',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AlterField(
            model_name='resource',
            name='title',
            field=models.TextField(),
        ),
    ]
