# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-10 21:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0004_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPrincipleAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('dreambuilder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fit.DreamBuilder')),
                ('principle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fit.CustomPrinciple')),
            ],
        ),
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('prompt', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurposeAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('dreambuilder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fit.DreamBuilder')),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fit.Purpose')),
            ],
        ),
        migrations.CreateModel(
            name='PurposeStatement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('dreambuilder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fit.DreamBuilder')),
            ],
        ),
        migrations.RemoveField(
            model_name='principleanswer',
            name='custom',
        ),
        migrations.AddField(
            model_name='principleanswer',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vision',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vision',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='vision',
            name='title',
            field=models.TextField(blank=True),
        ),
    ]
