# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-12 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0005_auto_20170110_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='dimension',
        ),
        migrations.AddField(
            model_name='resource',
            name='embed',
            field=models.TextField(blank=True, help_text='Full iframe embed code from YouTube or Vimeo.'),
        ),
        migrations.AddField(
            model_name='resource',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='thumbnail',
            field=models.FileField(null=True, upload_to='lib/%Y/%m/%d/thumbnail'),
        ),
        migrations.AddField(
            model_name='resource',
            name='upload',
            field=models.FileField(null=True, upload_to='lib/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
