# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-12 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0006_auto_20170112_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='thumbnail',
            field=models.FileField(blank=True, default='', upload_to='lib/%Y/%m/%d/thumbnail'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resource',
            name='upload',
            field=models.FileField(blank=True, default='', upload_to='lib/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
